/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.inspur.avro.model.java;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UrlFetchRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UrlFetchRequest\",\"namespace\":\"com.inspur.avro.model.java\",\"fields\":[{\"name\":\"taskId\",\"type\":[\"long\",\"null\"],\"doc\":\"任务ID\"},{\"name\":\"taskInstanceId\",\"type\":[\"string\",\"null\"],\"doc\":\"任务执行实例ID\"},{\"name\":\"url\",\"type\":[\"string\",\"null\"],\"doc\":\"目标url\"},{\"name\":\"urlType\",\"type\":{\"type\":\"enum\",\"name\":\"UrlType\",\"symbols\":[\"OTHER\",\"NAV\",\"LIST\",\"INFO\"]},\"doc\":\"目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它\"},{\"name\":\"urlHash\",\"type\":[\"int\",\"null\"],\"doc\":\"url的hashCode值\"},{\"name\":\"httpMethodName\",\"type\":[\"string\",\"null\"],\"doc\":\"请求方式\",\"default\":\"GET\"},{\"name\":\"maxDepth\",\"type\":[\"int\",\"null\"],\"doc\":\"爬取最大深度\"},{\"name\":\"currentDepth\",\"type\":[\"int\",\"null\"],\"doc\":\"当前爬取深度\"},{\"name\":\"failureCount\",\"type\":[\"int\",\"null\"],\"doc\":\"爬取失败次数\"},{\"name\":\"publishTime\",\"type\":[\"long\",\"null\"],\"doc\":\"发布时间\"},{\"name\":\"publisherId\",\"type\":[\"string\",\"null\"],\"doc\":\"发布人ID\"},{\"name\":\"downloadTool\",\"type\":[\"int\",\"null\"],\"doc\":\"下载工具:0 httpclinet,1 htmlunit\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 任务ID */
  @Deprecated public java.lang.Long taskId;
  /** 任务执行实例ID */
  @Deprecated public java.lang.CharSequence taskInstanceId;
  /** 目标url */
  @Deprecated public java.lang.CharSequence url;
  /** 目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它 */
  @Deprecated public com.inspur.avro.model.java.UrlType urlType;
  /** url的hashCode值 */
  @Deprecated public java.lang.Integer urlHash;
  /** 请求方式 */
  @Deprecated public java.lang.CharSequence httpMethodName;
  /** 爬取最大深度 */
  @Deprecated public java.lang.Integer maxDepth;
  /** 当前爬取深度 */
  @Deprecated public java.lang.Integer currentDepth;
  /** 爬取失败次数 */
  @Deprecated public java.lang.Integer failureCount;
  /** 发布时间 */
  @Deprecated public java.lang.Long publishTime;
  /** 发布人ID */
  @Deprecated public java.lang.CharSequence publisherId;
  /** 下载工具:0 httpclinet,1 htmlunit */
  @Deprecated public java.lang.Integer downloadTool;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public UrlFetchRequest() {}

  /**
   * All-args constructor.
   */
  public UrlFetchRequest(java.lang.Long taskId, java.lang.CharSequence taskInstanceId, java.lang.CharSequence url, com.inspur.avro.model.java.UrlType urlType, java.lang.Integer urlHash, java.lang.CharSequence httpMethodName, java.lang.Integer maxDepth, java.lang.Integer currentDepth, java.lang.Integer failureCount, java.lang.Long publishTime, java.lang.CharSequence publisherId, java.lang.Integer downloadTool) {
    this.taskId = taskId;
    this.taskInstanceId = taskInstanceId;
    this.url = url;
    this.urlType = urlType;
    this.urlHash = urlHash;
    this.httpMethodName = httpMethodName;
    this.maxDepth = maxDepth;
    this.currentDepth = currentDepth;
    this.failureCount = failureCount;
    this.publishTime = publishTime;
    this.publisherId = publisherId;
    this.downloadTool = downloadTool;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return taskId;
    case 1: return taskInstanceId;
    case 2: return url;
    case 3: return urlType;
    case 4: return urlHash;
    case 5: return httpMethodName;
    case 6: return maxDepth;
    case 7: return currentDepth;
    case 8: return failureCount;
    case 9: return publishTime;
    case 10: return publisherId;
    case 11: return downloadTool;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: taskId = (java.lang.Long)value$; break;
    case 1: taskInstanceId = (java.lang.CharSequence)value$; break;
    case 2: url = (java.lang.CharSequence)value$; break;
    case 3: urlType = (com.inspur.avro.model.java.UrlType)value$; break;
    case 4: urlHash = (java.lang.Integer)value$; break;
    case 5: httpMethodName = (java.lang.CharSequence)value$; break;
    case 6: maxDepth = (java.lang.Integer)value$; break;
    case 7: currentDepth = (java.lang.Integer)value$; break;
    case 8: failureCount = (java.lang.Integer)value$; break;
    case 9: publishTime = (java.lang.Long)value$; break;
    case 10: publisherId = (java.lang.CharSequence)value$; break;
    case 11: downloadTool = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'taskId' field.
   * 任务ID   */
  public java.lang.Long getTaskId() {
    return taskId;
  }

  /**
   * Sets the value of the 'taskId' field.
   * 任务ID   * @param value the value to set.
   */
  public void setTaskId(java.lang.Long value) {
    this.taskId = value;
  }

  /**
   * Gets the value of the 'taskInstanceId' field.
   * 任务执行实例ID   */
  public java.lang.CharSequence getTaskInstanceId() {
    return taskInstanceId;
  }

  /**
   * Sets the value of the 'taskInstanceId' field.
   * 任务执行实例ID   * @param value the value to set.
   */
  public void setTaskInstanceId(java.lang.CharSequence value) {
    this.taskInstanceId = value;
  }

  /**
   * Gets the value of the 'url' field.
   * 目标url   */
  public java.lang.CharSequence getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * 目标url   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'urlType' field.
   * 目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它   */
  public com.inspur.avro.model.java.UrlType getUrlType() {
    return urlType;
  }

  /**
   * Sets the value of the 'urlType' field.
   * 目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它   * @param value the value to set.
   */
  public void setUrlType(com.inspur.avro.model.java.UrlType value) {
    this.urlType = value;
  }

  /**
   * Gets the value of the 'urlHash' field.
   * url的hashCode值   */
  public java.lang.Integer getUrlHash() {
    return urlHash;
  }

  /**
   * Sets the value of the 'urlHash' field.
   * url的hashCode值   * @param value the value to set.
   */
  public void setUrlHash(java.lang.Integer value) {
    this.urlHash = value;
  }

  /**
   * Gets the value of the 'httpMethodName' field.
   * 请求方式   */
  public java.lang.CharSequence getHttpMethodName() {
    return httpMethodName;
  }

  /**
   * Sets the value of the 'httpMethodName' field.
   * 请求方式   * @param value the value to set.
   */
  public void setHttpMethodName(java.lang.CharSequence value) {
    this.httpMethodName = value;
  }

  /**
   * Gets the value of the 'maxDepth' field.
   * 爬取最大深度   */
  public java.lang.Integer getMaxDepth() {
    return maxDepth;
  }

  /**
   * Sets the value of the 'maxDepth' field.
   * 爬取最大深度   * @param value the value to set.
   */
  public void setMaxDepth(java.lang.Integer value) {
    this.maxDepth = value;
  }

  /**
   * Gets the value of the 'currentDepth' field.
   * 当前爬取深度   */
  public java.lang.Integer getCurrentDepth() {
    return currentDepth;
  }

  /**
   * Sets the value of the 'currentDepth' field.
   * 当前爬取深度   * @param value the value to set.
   */
  public void setCurrentDepth(java.lang.Integer value) {
    this.currentDepth = value;
  }

  /**
   * Gets the value of the 'failureCount' field.
   * 爬取失败次数   */
  public java.lang.Integer getFailureCount() {
    return failureCount;
  }

  /**
   * Sets the value of the 'failureCount' field.
   * 爬取失败次数   * @param value the value to set.
   */
  public void setFailureCount(java.lang.Integer value) {
    this.failureCount = value;
  }

  /**
   * Gets the value of the 'publishTime' field.
   * 发布时间   */
  public java.lang.Long getPublishTime() {
    return publishTime;
  }

  /**
   * Sets the value of the 'publishTime' field.
   * 发布时间   * @param value the value to set.
   */
  public void setPublishTime(java.lang.Long value) {
    this.publishTime = value;
  }

  /**
   * Gets the value of the 'publisherId' field.
   * 发布人ID   */
  public java.lang.CharSequence getPublisherId() {
    return publisherId;
  }

  /**
   * Sets the value of the 'publisherId' field.
   * 发布人ID   * @param value the value to set.
   */
  public void setPublisherId(java.lang.CharSequence value) {
    this.publisherId = value;
  }

  /**
   * Gets the value of the 'downloadTool' field.
   * 下载工具:0 httpclinet,1 htmlunit   */
  public java.lang.Integer getDownloadTool() {
    return downloadTool;
  }

  /**
   * Sets the value of the 'downloadTool' field.
   * 下载工具:0 httpclinet,1 htmlunit   * @param value the value to set.
   */
  public void setDownloadTool(java.lang.Integer value) {
    this.downloadTool = value;
  }

  /** Creates a new UrlFetchRequest RecordBuilder */
  public static com.inspur.avro.model.java.UrlFetchRequest.Builder newBuilder() {
    return new com.inspur.avro.model.java.UrlFetchRequest.Builder();
  }
  
  /** Creates a new UrlFetchRequest RecordBuilder by copying an existing Builder */
  public static com.inspur.avro.model.java.UrlFetchRequest.Builder newBuilder(com.inspur.avro.model.java.UrlFetchRequest.Builder other) {
    return new com.inspur.avro.model.java.UrlFetchRequest.Builder(other);
  }
  
  /** Creates a new UrlFetchRequest RecordBuilder by copying an existing UrlFetchRequest instance */
  public static com.inspur.avro.model.java.UrlFetchRequest.Builder newBuilder(com.inspur.avro.model.java.UrlFetchRequest other) {
    return new com.inspur.avro.model.java.UrlFetchRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for UrlFetchRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UrlFetchRequest>
    implements org.apache.avro.data.RecordBuilder<UrlFetchRequest> {

    private java.lang.Long taskId;
    private java.lang.CharSequence taskInstanceId;
    private java.lang.CharSequence url;
    private com.inspur.avro.model.java.UrlType urlType;
    private java.lang.Integer urlHash;
    private java.lang.CharSequence httpMethodName;
    private java.lang.Integer maxDepth;
    private java.lang.Integer currentDepth;
    private java.lang.Integer failureCount;
    private java.lang.Long publishTime;
    private java.lang.CharSequence publisherId;
    private java.lang.Integer downloadTool;

    /** Creates a new Builder */
    private Builder() {
      super(com.inspur.avro.model.java.UrlFetchRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.inspur.avro.model.java.UrlFetchRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.taskId)) {
        this.taskId = data().deepCopy(fields()[0].schema(), other.taskId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskInstanceId)) {
        this.taskInstanceId = data().deepCopy(fields()[1].schema(), other.taskInstanceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.url)) {
        this.url = data().deepCopy(fields()[2].schema(), other.url);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.urlType)) {
        this.urlType = data().deepCopy(fields()[3].schema(), other.urlType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.urlHash)) {
        this.urlHash = data().deepCopy(fields()[4].schema(), other.urlHash);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.httpMethodName)) {
        this.httpMethodName = data().deepCopy(fields()[5].schema(), other.httpMethodName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.maxDepth)) {
        this.maxDepth = data().deepCopy(fields()[6].schema(), other.maxDepth);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.currentDepth)) {
        this.currentDepth = data().deepCopy(fields()[7].schema(), other.currentDepth);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.failureCount)) {
        this.failureCount = data().deepCopy(fields()[8].schema(), other.failureCount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.publishTime)) {
        this.publishTime = data().deepCopy(fields()[9].schema(), other.publishTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.publisherId)) {
        this.publisherId = data().deepCopy(fields()[10].schema(), other.publisherId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.downloadTool)) {
        this.downloadTool = data().deepCopy(fields()[11].schema(), other.downloadTool);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UrlFetchRequest instance */
    private Builder(com.inspur.avro.model.java.UrlFetchRequest other) {
            super(com.inspur.avro.model.java.UrlFetchRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.taskId)) {
        this.taskId = data().deepCopy(fields()[0].schema(), other.taskId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskInstanceId)) {
        this.taskInstanceId = data().deepCopy(fields()[1].schema(), other.taskInstanceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.url)) {
        this.url = data().deepCopy(fields()[2].schema(), other.url);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.urlType)) {
        this.urlType = data().deepCopy(fields()[3].schema(), other.urlType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.urlHash)) {
        this.urlHash = data().deepCopy(fields()[4].schema(), other.urlHash);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.httpMethodName)) {
        this.httpMethodName = data().deepCopy(fields()[5].schema(), other.httpMethodName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.maxDepth)) {
        this.maxDepth = data().deepCopy(fields()[6].schema(), other.maxDepth);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.currentDepth)) {
        this.currentDepth = data().deepCopy(fields()[7].schema(), other.currentDepth);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.failureCount)) {
        this.failureCount = data().deepCopy(fields()[8].schema(), other.failureCount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.publishTime)) {
        this.publishTime = data().deepCopy(fields()[9].schema(), other.publishTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.publisherId)) {
        this.publisherId = data().deepCopy(fields()[10].schema(), other.publisherId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.downloadTool)) {
        this.downloadTool = data().deepCopy(fields()[11].schema(), other.downloadTool);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'taskId' field */
    public java.lang.Long getTaskId() {
      return taskId;
    }
    
    /** Sets the value of the 'taskId' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setTaskId(java.lang.Long value) {
      validate(fields()[0], value);
      this.taskId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'taskId' field has been set */
    public boolean hasTaskId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'taskId' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearTaskId() {
      taskId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'taskInstanceId' field */
    public java.lang.CharSequence getTaskInstanceId() {
      return taskInstanceId;
    }
    
    /** Sets the value of the 'taskInstanceId' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setTaskInstanceId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.taskInstanceId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'taskInstanceId' field has been set */
    public boolean hasTaskInstanceId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'taskInstanceId' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearTaskInstanceId() {
      taskInstanceId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'url' field */
    public java.lang.CharSequence getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.url = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'url' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearUrl() {
      url = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'urlType' field */
    public com.inspur.avro.model.java.UrlType getUrlType() {
      return urlType;
    }
    
    /** Sets the value of the 'urlType' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setUrlType(com.inspur.avro.model.java.UrlType value) {
      validate(fields()[3], value);
      this.urlType = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'urlType' field has been set */
    public boolean hasUrlType() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'urlType' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearUrlType() {
      urlType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'urlHash' field */
    public java.lang.Integer getUrlHash() {
      return urlHash;
    }
    
    /** Sets the value of the 'urlHash' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setUrlHash(java.lang.Integer value) {
      validate(fields()[4], value);
      this.urlHash = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'urlHash' field has been set */
    public boolean hasUrlHash() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'urlHash' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearUrlHash() {
      urlHash = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'httpMethodName' field */
    public java.lang.CharSequence getHttpMethodName() {
      return httpMethodName;
    }
    
    /** Sets the value of the 'httpMethodName' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setHttpMethodName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.httpMethodName = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'httpMethodName' field has been set */
    public boolean hasHttpMethodName() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'httpMethodName' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearHttpMethodName() {
      httpMethodName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'maxDepth' field */
    public java.lang.Integer getMaxDepth() {
      return maxDepth;
    }
    
    /** Sets the value of the 'maxDepth' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setMaxDepth(java.lang.Integer value) {
      validate(fields()[6], value);
      this.maxDepth = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'maxDepth' field has been set */
    public boolean hasMaxDepth() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'maxDepth' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearMaxDepth() {
      maxDepth = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'currentDepth' field */
    public java.lang.Integer getCurrentDepth() {
      return currentDepth;
    }
    
    /** Sets the value of the 'currentDepth' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setCurrentDepth(java.lang.Integer value) {
      validate(fields()[7], value);
      this.currentDepth = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'currentDepth' field has been set */
    public boolean hasCurrentDepth() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'currentDepth' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearCurrentDepth() {
      currentDepth = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'failureCount' field */
    public java.lang.Integer getFailureCount() {
      return failureCount;
    }
    
    /** Sets the value of the 'failureCount' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setFailureCount(java.lang.Integer value) {
      validate(fields()[8], value);
      this.failureCount = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'failureCount' field has been set */
    public boolean hasFailureCount() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'failureCount' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearFailureCount() {
      failureCount = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'publishTime' field */
    public java.lang.Long getPublishTime() {
      return publishTime;
    }
    
    /** Sets the value of the 'publishTime' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setPublishTime(java.lang.Long value) {
      validate(fields()[9], value);
      this.publishTime = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'publishTime' field has been set */
    public boolean hasPublishTime() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'publishTime' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearPublishTime() {
      publishTime = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'publisherId' field */
    public java.lang.CharSequence getPublisherId() {
      return publisherId;
    }
    
    /** Sets the value of the 'publisherId' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setPublisherId(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.publisherId = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'publisherId' field has been set */
    public boolean hasPublisherId() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'publisherId' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearPublisherId() {
      publisherId = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'downloadTool' field */
    public java.lang.Integer getDownloadTool() {
      return downloadTool;
    }
    
    /** Sets the value of the 'downloadTool' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder setDownloadTool(java.lang.Integer value) {
      validate(fields()[11], value);
      this.downloadTool = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'downloadTool' field has been set */
    public boolean hasDownloadTool() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'downloadTool' field */
    public com.inspur.avro.model.java.UrlFetchRequest.Builder clearDownloadTool() {
      downloadTool = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public UrlFetchRequest build() {
      try {
        UrlFetchRequest record = new UrlFetchRequest();
        record.taskId = fieldSetFlags()[0] ? this.taskId : (java.lang.Long) defaultValue(fields()[0]);
        record.taskInstanceId = fieldSetFlags()[1] ? this.taskInstanceId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.url = fieldSetFlags()[2] ? this.url : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.urlType = fieldSetFlags()[3] ? this.urlType : (com.inspur.avro.model.java.UrlType) defaultValue(fields()[3]);
        record.urlHash = fieldSetFlags()[4] ? this.urlHash : (java.lang.Integer) defaultValue(fields()[4]);
        record.httpMethodName = fieldSetFlags()[5] ? this.httpMethodName : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.maxDepth = fieldSetFlags()[6] ? this.maxDepth : (java.lang.Integer) defaultValue(fields()[6]);
        record.currentDepth = fieldSetFlags()[7] ? this.currentDepth : (java.lang.Integer) defaultValue(fields()[7]);
        record.failureCount = fieldSetFlags()[8] ? this.failureCount : (java.lang.Integer) defaultValue(fields()[8]);
        record.publishTime = fieldSetFlags()[9] ? this.publishTime : (java.lang.Long) defaultValue(fields()[9]);
        record.publisherId = fieldSetFlags()[10] ? this.publisherId : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.downloadTool = fieldSetFlags()[11] ? this.downloadTool : (java.lang.Integer) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
