/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.inspur.avro.model.java;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UrlParseRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UrlParseRequest\",\"namespace\":\"com.inspur.avro.model.java\",\"fields\":[{\"name\":\"taskId\",\"type\":[\"long\",\"null\"],\"doc\":\"任务ID\"},{\"name\":\"taskInstanceId\",\"type\":[\"string\",\"null\"],\"doc\":\"任务执行实例ID\"},{\"name\":\"url\",\"type\":[\"string\",\"null\"],\"doc\":\"目标URL\"},{\"name\":\"urlType\",\"type\":{\"type\":\"enum\",\"name\":\"UrlType\",\"symbols\":[\"OTHER\",\"NAV\",\"LIST\",\"INFO\"]},\"doc\":\"目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它\"},{\"name\":\"urlHash\",\"type\":[\"int\",\"null\"],\"doc\":\"url的hashCode值\"},{\"name\":\"maxDepth\",\"type\":[\"int\",\"null\"],\"doc\":\"爬取最大深度\"},{\"name\":\"currentDepth\",\"type\":[\"int\",\"null\"],\"doc\":\"当前爬取深度\"},{\"name\":\"domContent\",\"type\":[\"string\",\"null\"],\"doc\":\"爬取到的内容\"},{\"name\":\"publishTime\",\"type\":[\"long\",\"null\"],\"doc\":\"发布时间\"},{\"name\":\"publisherId\",\"type\":[\"string\",\"null\"],\"doc\":\"发布人ID\"},{\"name\":\"httpHeader\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"doc\":\"爬取结果中http的header内容\"},{\"name\":\"httpStatus\",\"type\":[\"string\",\"null\"],\"doc\":\"爬取结果中http返回的状态码\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 任务ID */
  @Deprecated public java.lang.Long taskId;
  /** 任务执行实例ID */
  @Deprecated public java.lang.CharSequence taskInstanceId;
  /** 目标URL */
  @Deprecated public java.lang.CharSequence url;
  /** 目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它 */
  @Deprecated public com.inspur.avro.model.java.UrlType urlType;
  /** url的hashCode值 */
  @Deprecated public java.lang.Integer urlHash;
  /** 爬取最大深度 */
  @Deprecated public java.lang.Integer maxDepth;
  /** 当前爬取深度 */
  @Deprecated public java.lang.Integer currentDepth;
  /** 爬取到的内容 */
  @Deprecated public java.lang.CharSequence domContent;
  /** 发布时间 */
  @Deprecated public java.lang.Long publishTime;
  /** 发布人ID */
  @Deprecated public java.lang.CharSequence publisherId;
  /** 爬取结果中http的header内容 */
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> httpHeader;
  /** 爬取结果中http返回的状态码 */
  @Deprecated public java.lang.CharSequence httpStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public UrlParseRequest() {}

  /**
   * All-args constructor.
   */
  public UrlParseRequest(java.lang.Long taskId, java.lang.CharSequence taskInstanceId, java.lang.CharSequence url, com.inspur.avro.model.java.UrlType urlType, java.lang.Integer urlHash, java.lang.Integer maxDepth, java.lang.Integer currentDepth, java.lang.CharSequence domContent, java.lang.Long publishTime, java.lang.CharSequence publisherId, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> httpHeader, java.lang.CharSequence httpStatus) {
    this.taskId = taskId;
    this.taskInstanceId = taskInstanceId;
    this.url = url;
    this.urlType = urlType;
    this.urlHash = urlHash;
    this.maxDepth = maxDepth;
    this.currentDepth = currentDepth;
    this.domContent = domContent;
    this.publishTime = publishTime;
    this.publisherId = publisherId;
    this.httpHeader = httpHeader;
    this.httpStatus = httpStatus;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return taskId;
    case 1: return taskInstanceId;
    case 2: return url;
    case 3: return urlType;
    case 4: return urlHash;
    case 5: return maxDepth;
    case 6: return currentDepth;
    case 7: return domContent;
    case 8: return publishTime;
    case 9: return publisherId;
    case 10: return httpHeader;
    case 11: return httpStatus;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: taskId = (java.lang.Long)value$; break;
    case 1: taskInstanceId = (java.lang.CharSequence)value$; break;
    case 2: url = (java.lang.CharSequence)value$; break;
    case 3: urlType = (com.inspur.avro.model.java.UrlType)value$; break;
    case 4: urlHash = (java.lang.Integer)value$; break;
    case 5: maxDepth = (java.lang.Integer)value$; break;
    case 6: currentDepth = (java.lang.Integer)value$; break;
    case 7: domContent = (java.lang.CharSequence)value$; break;
    case 8: publishTime = (java.lang.Long)value$; break;
    case 9: publisherId = (java.lang.CharSequence)value$; break;
    case 10: httpHeader = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 11: httpStatus = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'taskId' field.
   * 任务ID   */
  public java.lang.Long getTaskId() {
    return taskId;
  }

  /**
   * Sets the value of the 'taskId' field.
   * 任务ID   * @param value the value to set.
   */
  public void setTaskId(java.lang.Long value) {
    this.taskId = value;
  }

  /**
   * Gets the value of the 'taskInstanceId' field.
   * 任务执行实例ID   */
  public java.lang.CharSequence getTaskInstanceId() {
    return taskInstanceId;
  }

  /**
   * Sets the value of the 'taskInstanceId' field.
   * 任务执行实例ID   * @param value the value to set.
   */
  public void setTaskInstanceId(java.lang.CharSequence value) {
    this.taskInstanceId = value;
  }

  /**
   * Gets the value of the 'url' field.
   * 目标URL   */
  public java.lang.CharSequence getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * 目标URL   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'urlType' field.
   * 目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它   */
  public com.inspur.avro.model.java.UrlType getUrlType() {
    return urlType;
  }

  /**
   * Sets the value of the 'urlType' field.
   * 目标url的类型,NAV:导航页,LIST:翻页列表,INFO:详情页,OTHER:其它   * @param value the value to set.
   */
  public void setUrlType(com.inspur.avro.model.java.UrlType value) {
    this.urlType = value;
  }

  /**
   * Gets the value of the 'urlHash' field.
   * url的hashCode值   */
  public java.lang.Integer getUrlHash() {
    return urlHash;
  }

  /**
   * Sets the value of the 'urlHash' field.
   * url的hashCode值   * @param value the value to set.
   */
  public void setUrlHash(java.lang.Integer value) {
    this.urlHash = value;
  }

  /**
   * Gets the value of the 'maxDepth' field.
   * 爬取最大深度   */
  public java.lang.Integer getMaxDepth() {
    return maxDepth;
  }

  /**
   * Sets the value of the 'maxDepth' field.
   * 爬取最大深度   * @param value the value to set.
   */
  public void setMaxDepth(java.lang.Integer value) {
    this.maxDepth = value;
  }

  /**
   * Gets the value of the 'currentDepth' field.
   * 当前爬取深度   */
  public java.lang.Integer getCurrentDepth() {
    return currentDepth;
  }

  /**
   * Sets the value of the 'currentDepth' field.
   * 当前爬取深度   * @param value the value to set.
   */
  public void setCurrentDepth(java.lang.Integer value) {
    this.currentDepth = value;
  }

  /**
   * Gets the value of the 'domContent' field.
   * 爬取到的内容   */
  public java.lang.CharSequence getDomContent() {
    return domContent;
  }

  /**
   * Sets the value of the 'domContent' field.
   * 爬取到的内容   * @param value the value to set.
   */
  public void setDomContent(java.lang.CharSequence value) {
    this.domContent = value;
  }

  /**
   * Gets the value of the 'publishTime' field.
   * 发布时间   */
  public java.lang.Long getPublishTime() {
    return publishTime;
  }

  /**
   * Sets the value of the 'publishTime' field.
   * 发布时间   * @param value the value to set.
   */
  public void setPublishTime(java.lang.Long value) {
    this.publishTime = value;
  }

  /**
   * Gets the value of the 'publisherId' field.
   * 发布人ID   */
  public java.lang.CharSequence getPublisherId() {
    return publisherId;
  }

  /**
   * Sets the value of the 'publisherId' field.
   * 发布人ID   * @param value the value to set.
   */
  public void setPublisherId(java.lang.CharSequence value) {
    this.publisherId = value;
  }

  /**
   * Gets the value of the 'httpHeader' field.
   * 爬取结果中http的header内容   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getHttpHeader() {
    return httpHeader;
  }

  /**
   * Sets the value of the 'httpHeader' field.
   * 爬取结果中http的header内容   * @param value the value to set.
   */
  public void setHttpHeader(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.httpHeader = value;
  }

  /**
   * Gets the value of the 'httpStatus' field.
   * 爬取结果中http返回的状态码   */
  public java.lang.CharSequence getHttpStatus() {
    return httpStatus;
  }

  /**
   * Sets the value of the 'httpStatus' field.
   * 爬取结果中http返回的状态码   * @param value the value to set.
   */
  public void setHttpStatus(java.lang.CharSequence value) {
    this.httpStatus = value;
  }

  /** Creates a new UrlParseRequest RecordBuilder */
  public static com.inspur.avro.model.java.UrlParseRequest.Builder newBuilder() {
    return new com.inspur.avro.model.java.UrlParseRequest.Builder();
  }
  
  /** Creates a new UrlParseRequest RecordBuilder by copying an existing Builder */
  public static com.inspur.avro.model.java.UrlParseRequest.Builder newBuilder(com.inspur.avro.model.java.UrlParseRequest.Builder other) {
    return new com.inspur.avro.model.java.UrlParseRequest.Builder(other);
  }
  
  /** Creates a new UrlParseRequest RecordBuilder by copying an existing UrlParseRequest instance */
  public static com.inspur.avro.model.java.UrlParseRequest.Builder newBuilder(com.inspur.avro.model.java.UrlParseRequest other) {
    return new com.inspur.avro.model.java.UrlParseRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for UrlParseRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UrlParseRequest>
    implements org.apache.avro.data.RecordBuilder<UrlParseRequest> {

    private java.lang.Long taskId;
    private java.lang.CharSequence taskInstanceId;
    private java.lang.CharSequence url;
    private com.inspur.avro.model.java.UrlType urlType;
    private java.lang.Integer urlHash;
    private java.lang.Integer maxDepth;
    private java.lang.Integer currentDepth;
    private java.lang.CharSequence domContent;
    private java.lang.Long publishTime;
    private java.lang.CharSequence publisherId;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> httpHeader;
    private java.lang.CharSequence httpStatus;

    /** Creates a new Builder */
    private Builder() {
      super(com.inspur.avro.model.java.UrlParseRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.inspur.avro.model.java.UrlParseRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.taskId)) {
        this.taskId = data().deepCopy(fields()[0].schema(), other.taskId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskInstanceId)) {
        this.taskInstanceId = data().deepCopy(fields()[1].schema(), other.taskInstanceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.url)) {
        this.url = data().deepCopy(fields()[2].schema(), other.url);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.urlType)) {
        this.urlType = data().deepCopy(fields()[3].schema(), other.urlType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.urlHash)) {
        this.urlHash = data().deepCopy(fields()[4].schema(), other.urlHash);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.maxDepth)) {
        this.maxDepth = data().deepCopy(fields()[5].schema(), other.maxDepth);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.currentDepth)) {
        this.currentDepth = data().deepCopy(fields()[6].schema(), other.currentDepth);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.domContent)) {
        this.domContent = data().deepCopy(fields()[7].schema(), other.domContent);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.publishTime)) {
        this.publishTime = data().deepCopy(fields()[8].schema(), other.publishTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.publisherId)) {
        this.publisherId = data().deepCopy(fields()[9].schema(), other.publisherId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.httpHeader)) {
        this.httpHeader = data().deepCopy(fields()[10].schema(), other.httpHeader);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.httpStatus)) {
        this.httpStatus = data().deepCopy(fields()[11].schema(), other.httpStatus);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UrlParseRequest instance */
    private Builder(com.inspur.avro.model.java.UrlParseRequest other) {
            super(com.inspur.avro.model.java.UrlParseRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.taskId)) {
        this.taskId = data().deepCopy(fields()[0].schema(), other.taskId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskInstanceId)) {
        this.taskInstanceId = data().deepCopy(fields()[1].schema(), other.taskInstanceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.url)) {
        this.url = data().deepCopy(fields()[2].schema(), other.url);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.urlType)) {
        this.urlType = data().deepCopy(fields()[3].schema(), other.urlType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.urlHash)) {
        this.urlHash = data().deepCopy(fields()[4].schema(), other.urlHash);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.maxDepth)) {
        this.maxDepth = data().deepCopy(fields()[5].schema(), other.maxDepth);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.currentDepth)) {
        this.currentDepth = data().deepCopy(fields()[6].schema(), other.currentDepth);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.domContent)) {
        this.domContent = data().deepCopy(fields()[7].schema(), other.domContent);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.publishTime)) {
        this.publishTime = data().deepCopy(fields()[8].schema(), other.publishTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.publisherId)) {
        this.publisherId = data().deepCopy(fields()[9].schema(), other.publisherId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.httpHeader)) {
        this.httpHeader = data().deepCopy(fields()[10].schema(), other.httpHeader);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.httpStatus)) {
        this.httpStatus = data().deepCopy(fields()[11].schema(), other.httpStatus);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'taskId' field */
    public java.lang.Long getTaskId() {
      return taskId;
    }
    
    /** Sets the value of the 'taskId' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setTaskId(java.lang.Long value) {
      validate(fields()[0], value);
      this.taskId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'taskId' field has been set */
    public boolean hasTaskId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'taskId' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearTaskId() {
      taskId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'taskInstanceId' field */
    public java.lang.CharSequence getTaskInstanceId() {
      return taskInstanceId;
    }
    
    /** Sets the value of the 'taskInstanceId' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setTaskInstanceId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.taskInstanceId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'taskInstanceId' field has been set */
    public boolean hasTaskInstanceId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'taskInstanceId' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearTaskInstanceId() {
      taskInstanceId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'url' field */
    public java.lang.CharSequence getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.url = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'url' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearUrl() {
      url = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'urlType' field */
    public com.inspur.avro.model.java.UrlType getUrlType() {
      return urlType;
    }
    
    /** Sets the value of the 'urlType' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setUrlType(com.inspur.avro.model.java.UrlType value) {
      validate(fields()[3], value);
      this.urlType = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'urlType' field has been set */
    public boolean hasUrlType() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'urlType' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearUrlType() {
      urlType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'urlHash' field */
    public java.lang.Integer getUrlHash() {
      return urlHash;
    }
    
    /** Sets the value of the 'urlHash' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setUrlHash(java.lang.Integer value) {
      validate(fields()[4], value);
      this.urlHash = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'urlHash' field has been set */
    public boolean hasUrlHash() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'urlHash' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearUrlHash() {
      urlHash = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'maxDepth' field */
    public java.lang.Integer getMaxDepth() {
      return maxDepth;
    }
    
    /** Sets the value of the 'maxDepth' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setMaxDepth(java.lang.Integer value) {
      validate(fields()[5], value);
      this.maxDepth = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'maxDepth' field has been set */
    public boolean hasMaxDepth() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'maxDepth' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearMaxDepth() {
      maxDepth = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'currentDepth' field */
    public java.lang.Integer getCurrentDepth() {
      return currentDepth;
    }
    
    /** Sets the value of the 'currentDepth' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setCurrentDepth(java.lang.Integer value) {
      validate(fields()[6], value);
      this.currentDepth = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'currentDepth' field has been set */
    public boolean hasCurrentDepth() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'currentDepth' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearCurrentDepth() {
      currentDepth = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'domContent' field */
    public java.lang.CharSequence getDomContent() {
      return domContent;
    }
    
    /** Sets the value of the 'domContent' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setDomContent(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.domContent = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'domContent' field has been set */
    public boolean hasDomContent() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'domContent' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearDomContent() {
      domContent = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'publishTime' field */
    public java.lang.Long getPublishTime() {
      return publishTime;
    }
    
    /** Sets the value of the 'publishTime' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setPublishTime(java.lang.Long value) {
      validate(fields()[8], value);
      this.publishTime = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'publishTime' field has been set */
    public boolean hasPublishTime() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'publishTime' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearPublishTime() {
      publishTime = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'publisherId' field */
    public java.lang.CharSequence getPublisherId() {
      return publisherId;
    }
    
    /** Sets the value of the 'publisherId' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setPublisherId(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.publisherId = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'publisherId' field has been set */
    public boolean hasPublisherId() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'publisherId' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearPublisherId() {
      publisherId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'httpHeader' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getHttpHeader() {
      return httpHeader;
    }
    
    /** Sets the value of the 'httpHeader' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setHttpHeader(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[10], value);
      this.httpHeader = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'httpHeader' field has been set */
    public boolean hasHttpHeader() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'httpHeader' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearHttpHeader() {
      httpHeader = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'httpStatus' field */
    public java.lang.CharSequence getHttpStatus() {
      return httpStatus;
    }
    
    /** Sets the value of the 'httpStatus' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder setHttpStatus(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.httpStatus = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'httpStatus' field has been set */
    public boolean hasHttpStatus() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'httpStatus' field */
    public com.inspur.avro.model.java.UrlParseRequest.Builder clearHttpStatus() {
      httpStatus = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public UrlParseRequest build() {
      try {
        UrlParseRequest record = new UrlParseRequest();
        record.taskId = fieldSetFlags()[0] ? this.taskId : (java.lang.Long) defaultValue(fields()[0]);
        record.taskInstanceId = fieldSetFlags()[1] ? this.taskInstanceId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.url = fieldSetFlags()[2] ? this.url : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.urlType = fieldSetFlags()[3] ? this.urlType : (com.inspur.avro.model.java.UrlType) defaultValue(fields()[3]);
        record.urlHash = fieldSetFlags()[4] ? this.urlHash : (java.lang.Integer) defaultValue(fields()[4]);
        record.maxDepth = fieldSetFlags()[5] ? this.maxDepth : (java.lang.Integer) defaultValue(fields()[5]);
        record.currentDepth = fieldSetFlags()[6] ? this.currentDepth : (java.lang.Integer) defaultValue(fields()[6]);
        record.domContent = fieldSetFlags()[7] ? this.domContent : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.publishTime = fieldSetFlags()[8] ? this.publishTime : (java.lang.Long) defaultValue(fields()[8]);
        record.publisherId = fieldSetFlags()[9] ? this.publisherId : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.httpHeader = fieldSetFlags()[10] ? this.httpHeader : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[10]);
        record.httpStatus = fieldSetFlags()[11] ? this.httpStatus : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
