/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.inspur.avro.model.java;  
@SuppressWarnings("all") 
@org.apache.avro.specific.AvroGenerated
public enum UrlType { 
  OTHER, NAV, LIST, INFO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UrlType\",\"namespace\":\"com.inspur.avro.model.java\",\"symbols\":[\"OTHER\",\"NAV\",\"LIST\",\"INFO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
